---
- name: Mccode-job-runner builder
  hosts: all
  vars:
     # User
    user: centos
    package_version: latest

    jobio:
      name: jobio
      version: 0.0.0a9

    ansible_bender:
      base_image: "docker.io/nielsbohr/mcstas-mcxtrace:{{ package_version }}"
      working_container:
        user: root
      target_image:
        name: "docker.io/nielsbohr/mccode-job-runner:{{ package_version }}"
        entrypoint: '["/tini", "-g", "--"]'
        cmd: "jobio"
        user: "{{ user }}"
        working_dir: "/home/{{ user }}"
        environment:
          PATH: "/home/{{user }}/.local/bin:$PATH"
      layering: false
      
  tasks:
  - name: install jobio
    pip:
      executable: /usr/local/bin/pip3
      name:
        - "{{ jobio.name }}=={{ jobio.version }}"
      state: present
