---
- name: Mccode-job-runner builder
  hosts: all
  vars:

    ansible_python_interpreter: /usr/bin/python
    package_version: latest

    jobio:
      name: jobio
      dest: /tmp/jobio
      repo: https://github.com/rasmunk/jobio.git

    ansible_bender:
      base_image: "docker.io/nielsbohr/mcstas-mcxtrace:{{ package_version }}"
      target_image:
        name: "docker.io/nielsbohr/mccode-job-runner:{{ package_version }}"
        entrypoint: '["/tini", "-g", "--"]'
        cmd: "jobio"
      layering: false

  tasks:
  - name: install packages
    yum:
      state: present
      name:
        - git
        - bind-utils

  - name: clone jobio
    git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
      clone: yes
    with_items:
      - { repo: "{{ jobio.repo }}", dest: "{{ jobio.dest }}" }

  - name: install jobio
    shell:
      cmd: "/usr/local/bin/python3 setup.py install"
      chdir: "{{ jobio.dest }}"
